services:
  db:
    image: postgres:17.5
    container_name: tg_posts_psql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}' ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: tg_posts_app
    env_file:
      - .env
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c " python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 & python -m bot.bot "

volumes:
  postgres_data:
